apiVersion: apps/v1
kind: Deployment
metadata:
  name: personalized-learning
spec:
  replicas: 3
  selector:
    matchLabels:
      app: personalized-learning
  template:
    metadata:
      labels:
        app: personalized-learning
    spec:
      containers:
      - name: app
        image: personalized-learning:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: personalized-learning
spec:
  selector:
    app: personalized-learning
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
